# Generated by Django 6.1 on 2026-09-07 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False, verbose_name='aceptada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de amistad',
                'verbose_name_plural': 'solicitudes de amistad',
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='una_solicitud_por_par_tonnage')],
            },
        ),
    ]
