# Generated by Django 6.1 on 2026-08-30 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('region', models.CharField(choices=[('upper', 'Tren superior'), ('lower', 'Tren inferior'), ('core', 'Core')], max_length=10, verbose_name='región')),
            ],
            options={
                'verbose_name': 'grupo muscular',
                'verbose_name_plural': 'grupos musculares',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='número de serie')),
                ('set_type', models.CharField(choices=[('warmup', '🔵 Calentamiento'), ('working', '🟢 Trabajo'), ('approach', '🟡 Aproximación'), ('top_set', '🔴 Top set'), ('backoff', '🟣 Back-off'), ('drop_set', '⚫ Drop set'), ('rest_pause', '🟠 Rest-pause'), ('myo_reps', '🔵 Myo-reps'), ('failure', '⚪ Fallo'), ('custom', 'Personalizada')], default='working', max_length=12, verbose_name='tipo de serie')),
                ('custom_type_label', models.CharField(blank=True, max_length=40, verbose_name='etiqueta personalizada')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='peso (kg)')),
                ('input_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2, verbose_name='unidad introducida')),
                ('is_assisted', models.BooleanField(default=False, help_text='Máquina de asistencia: el peso resta carga en vez de sumarla (dominadas/fondos asistidos).', verbose_name='asistido')),
                ('reps_performed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='repeticiones realizadas')),
                ('reps_target', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='repeticiones objetivo')),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='RPE')),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='RIR')),
                ('percent_1rm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% 1RM')),
                ('estimated_1rm_kg', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='1RM estimado (kg)')),
                ('tempo', models.CharField(blank=True, help_text='Excéntrica-pausa-concéntrica-pausa, ej. «3-1-2-0».', max_length=20, verbose_name='tempo')),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='descanso previo (s)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('completed', models.BooleanField(default=True, verbose_name='completada')),
                ('is_pr', models.BooleanField(default=False, editable=False, verbose_name='es un PR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
                'ordering': ['workout_exercise', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='BodyWeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='peso (kg)')),
                ('input_unit', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2, verbose_name='unidad introducida')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% grasa corporal')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyweight_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'entrada de peso corporal',
                'verbose_name_plural': 'entradas de peso corporal',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='slug')),
                ('equipment', models.CharField(choices=[('barbell', 'Barra'), ('dumbbell', 'Mancuerna'), ('machine', 'Máquina'), ('cable', 'Polea'), ('bodyweight', 'Peso corporal'), ('kettlebell', 'Kettlebell'), ('band', 'Bandas'), ('other', 'Otro')], max_length=12, verbose_name='equipo')),
                ('category', models.CharField(choices=[('compound', 'Multiarticular'), ('isolation', 'Analítico')], default='compound', max_length=10, verbose_name='categoría')),
                ('unilateral', models.BooleanField(default=False, help_text='Se entrena un lado a la vez (ej. zancadas, remo a un brazo).', verbose_name='unilateral')),
                ('instructions', models.TextField(blank=True, verbose_name='instrucciones')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarca para archivarlo sin perder el historial de series ya registradas.', verbose_name='activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL, verbose_name='creado por (vacío = catálogo global)')),
                ('primary_muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_exercises', to='training.musclegroup', verbose_name='músculo principal')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='training.musclegroup', verbose_name='músculos secundarios')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('exercise_pr', 'PR de ejercicio'), ('bodyweight', 'Peso corporal'), ('frequency', 'Frecuencia semanal'), ('custom', 'Personalizado')], max_length=12, verbose_name='tipo')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('target_value_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor objetivo (kg)')),
                ('target_reps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='repeticiones objetivo')),
                ('target_workouts_per_week', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='entrenamientos/semana objetivo')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='fecha objetivo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('achieved', models.BooleanField(default=False, verbose_name='conseguido')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='conseguido el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='training.exercise', verbose_name='ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'ordering': ['achieved', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'rutina',
                'verbose_name_plural': 'rutinas',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. «Día A · Empuje», «Piernas», «Full body».', max_length=100, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.routine', verbose_name='rutina')),
            ],
            options={
                'verbose_name': 'día de rutina',
                'verbose_name_plural': 'días de rutina',
                'ordering': ['routine', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('superset_group', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='grupo de superserie')),
                ('target_sets', models.PositiveSmallIntegerField(default=3, verbose_name='series objetivo')),
                ('target_reps_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='reps objetivo (mín.)')),
                ('target_reps_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='reps objetivo (máx.)')),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='RPE objetivo')),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='descanso (s)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='training.exercise', verbose_name='ejercicio')),
                ('routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.routineday', verbose_name='día')),
            ],
            options={
                'verbose_name': 'ejercicio de rutina',
                'verbose_name_plural': 'ejercicios de rutina',
                'ordering': ['routine_day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. «Pecho + tríceps». Se rellena solo desde el día de rutina si se elige uno.', max_length=150, verbose_name='nombre')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='hora de inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('status', models.CharField(choices=[('in_progress', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='in_progress', max_length=12, verbose_name='estado')),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Agotado 😩'), (2, 'Bajo 😐'), (3, 'Normal 🙂'), (4, 'Con ganas 💪'), (5, 'A tope 🔥')], null=True, verbose_name='estado de energía')),
                ('rpe_session', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='RPE general')),
                ('bodyweight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso corporal ese día (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='training.routine', verbose_name='rutina')),
                ('routine_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='training.routineday', verbose_name='día de rutina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'entrenamiento',
                'verbose_name_plural': 'entrenamientos',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weight', 'Peso máximo'), ('est_1rm', '1RM estimado'), ('reps', 'Repeticiones máximas'), ('volume_session', 'Volumen en una sesión')], max_length=15, verbose_name='tipo')),
                ('value_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor (kg)')),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='repeticiones')),
                ('achieved_at', models.DateTimeField(verbose_name='conseguido')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='training.exercise', verbose_name='ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('set_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='training.setentry', verbose_name='serie de origen')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='training.workout', verbose_name='entrenamiento de origen')),
            ],
            options={
                'verbose_name': 'récord personal',
                'verbose_name_plural': 'récords personales',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('superset_group', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='grupo de superserie')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_appearances', to='training.exercise', verbose_name='ejercicio')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.workout', verbose_name='entrenamiento')),
            ],
            options={
                'verbose_name': 'ejercicio del entrenamiento',
                'verbose_name_plural': 'ejercicios del entrenamiento',
                'ordering': ['workout', 'order'],
            },
        ),
        migrations.AddField(
            model_name='setentry',
            name='workout_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.workoutexercise', verbose_name='ejercicio del entrenamiento'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name',), name='nombre_unico_catalogo_global'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('created_by', 'name'), name='nombre_unico_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='personalrecord',
            constraint=models.UniqueConstraint(fields=('user', 'exercise', 'kind'), name='un_pr_actual_por_tipo_y_ejercicio'),
        ),
        migrations.AddConstraint(
            model_name='setentry',
            constraint=models.UniqueConstraint(fields=('workout_exercise', 'set_number'), name='numero_serie_unico_por_ejercicio'),
        ),
    ]
