# Generated by Django 6.1 on 2026-09-08 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('calories_per_100g', models.PositiveSmallIntegerField(verbose_name='kcal / 100g')),
                ('protein_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='proteína / 100g')),
                ('carbs_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='carbohidratos / 100g')),
                ('fat_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='grasa / 100g')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL, verbose_name='creado por (vacío = catálogo global)')),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'alimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Comida'), ('dinner', 'Cena'), ('snack', 'Snack')], default='lunch', max_length=10, verbose_name='comida')),
                ('quantity_g', models.PositiveSmallIntegerField(verbose_name='cantidad (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_entries', to='training.food', verbose_name='alimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'entrada de comida',
                'verbose_name_plural': 'entradas de comida',
                'ordering': ['date', 'meal_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='kcal/día objetivo')),
                ('daily_protein_g', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='proteína (g)/día objetivo')),
                ('daily_carbs_g', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='carbohidratos (g)/día objetivo')),
                ('daily_fat_g', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='grasa (g)/día objetivo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'objetivo nutricional',
                'verbose_name_plural': 'objetivos nutricionales',
            },
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name',), name='nombre_unico_catalogo_alimentos_global'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('created_by', 'name'), name='nombre_unico_por_usuario_alimentos'),
        ),
    ]
