# Generated by Django 6.1 on 2026-09-08 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_food_mealentry_nutritiongoal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_code', models.CharField(max_length=40, verbose_name='misión')),
                ('period_start', models.DateField(verbose_name='periodo')),
                ('points', models.PositiveIntegerField(verbose_name='XP')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='conseguida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'misión completada',
                'verbose_name_plural': 'misiones completadas',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'quest_code', 'period_start'), name='una_vez_por_usuario_mision_y_periodo')],
            },
        ),
    ]
